APP.addWeek({
  id: "w4",
  num: 4,
  title: "Assembling Human Resources for Your Startup",
  lecture: {
    label: "Lecture 4 — Prof. Dr. Wouter Stam",
    date: "Feb 23, 2026",
    sections: [
      {
        title: "Go Solo or Build a Team?",
        body: "Entrepreneurs face a fundamental early decision: should they found solo or assemble a team?\n\n**Tradeoffs by team size:**\n\n- **Solo founder** — Faster decision-making, full equity ownership, no co-founder conflicts; but may lack critical resources and has no check on thinking\n\n- **Two founders** — Can fill skill gaps, \"two heads are better than one,\" emotional support; but coordination costs slow decisions and conflicts arise\n\n- **Three founders** — Third founder can mediate disputes; but even higher coordination costs and clash risk\n\n**Case Study: Ockham Technologies** — Jim Triandiflou (CEO, \"outside stuff\": sales, marketing) partnered with Ken Burrows (COO, \"inside stuff\": engineering, finance, HR), Mike Meisenheimer (product specification/management), and Ron Hardin (lead development). The case illustrates how complementary roles can be distributed across a founding team.\n\n> Conflict in founding teams arises in four domains: **financial issues** (equity, compensation), **power issues** (roles, decision-making, CEO control), **venture planning** (strategic direction, growth orientation, risk propensity), and **interpersonal conflict** (ethical lapses, commitment gaps, clashing styles, divergent goals)."
      },
      {
        title: "Holistic Assessment of Co-Founders",
        body: "Founders often **overemphasize complementarity in skills** when searching for co-founders. Education and work experience are easier to assess, but entrepreneurs must also evaluate compatibility in **goals, values, and personality**.\n\nEmpirical evidence on founding team homogeneity:\n\n- All-male or all-female teams are **5 times more likely** than would occur by chance\n\n- Ethnically homogeneous teams are **27 times more likely** than by chance\n\nThis suggests founders do not take advantage of the benefits of diversity — they gravitate toward people who are similar to themselves.\n\n> **Eesley, Hsu & Roberts (2014)** studied 2,067 MIT-founded ventures and found that on average, diverse teams perform better. However, the optimal team composition is **contingent** on the venture's innovation strategy and commercialization environment — diversity is not universally superior."
      },
      {
        title: "Founding with Friends",
        body: "Starting a company with friends offers potential benefits but also distinctive risks.\n\n**Benefits:**\n\n- No need to spend time learning about each other's backgrounds and abilities\n\n- Faster decision-making and less friction due to pre-existing trust\n\n**Risks:**\n\n- Friends assume \"we know each other well\" and are more hesitant to address problems — they don't want to risk the friendship\n\n- Friends often have more similar backgrounds and connections, creating a **capability gap**\n\n> \"I have seen several startups where star sales-people figure they can use their experience to cofound a successful company... At first, sales take off, and the friendship continues. Down the road, they find out their best friends all share the same business skills and — unfortunately — the same weaknesses.\" (Wasserman, 2012)\n\n**Implications:** Find an optimal balance of team diversity that fits your needs and context. Diverse teams perform better in **high turbulence and uncertainty**. Use multiple channels — family connections, school affiliations, former colleagues, networking events — to find co-founders who are different from you."
      },
      {
        title: "Dividing the Pie: Equity Splits",
        body: "Equity distribution is one of the most consequential and emotionally charged decisions a founding team faces.\n\n> \"There are thousands of issues that a startup has to deal with. Equity, the distribution of shares in the company, is the nuclear issue. The X-ray issue. The one that opens things up right to the core...\" (Ashbrook, 2000)\n\n**When is someone a founder?** Consider those who: come up with the idea (technical idea, business idea, strategic vision), execute (build/sell product, raise funding, hire people), and are committed (contribute capital, early involvement, full-time dedication).\n\n**How to split equity:**\n\n- Amount of capital invested is quite arbitrary and doesn't capture other contributions (idea generation, business model validation, expertise, network connections, writing the business plan)\n\n- Consider each founder's **past contributions, future role, career risk taken, and financial demands**\n\n**Timing matters critically:**\n\n- **Early split disadvantages:** roles not fully developed, lack of knowledge about each other's work habits, founders share equally despite unequal contributions\n\n- **Early split advantages:** solidifies expectations, can be done before external funding pressure, can always renegotiate\n\n**Dynamic agreements** offer a middle ground: set guidelines and milestones for equity allocation, use **vesting schedules** (time-based or milestone-based), and set aside equity to be apportioned later.\n\n> **Breugst, Patzelt & Rathgeber (2015)** found that **perceived justice** is the key mechanism explaining how equity distribution shapes team interactions. High perceived justice leads to positive team interaction spirals; low perceived justice leads to negative spirals."
      },
      {
        title: "Dividing Roles in Founding Teams",
        body: "The \"equal partners\" model has both strengths and weaknesses:\n\n**Pros of equal partnership:**\n\n- Most valuable when decisions require input from the entire team\n\n- Less disruption when one founder leaves\n\n**Cons of equal partnership:**\n\n- Employees like to know who is the leader\n\n- Boards often require a single point of contact\n\n> \"My chief regret is that we didn't adjust our management structure quickly enough to adapt to the changing situation. My view now is that, as an early startup where the imperative is avoiding making the big mistake, having a group of equal partners with divergent views is a good thing. When the time comes that your business is working and you need to act fast and make decisions quickly to grow and seize opportunities, the best thing is to have a dictatorship.\" (Wasserman, 2012)\n\n**Implications:** Seek a balance between egalitarianism and hierarchy. First employ a consensus approach, then define who has veto power for key decisions. Assign a mediator who can resolve conflicts. The need for **hierarchical decision-making grows over time** as the venture becomes larger and more complex."
      },
      {
        title: "The Hiring Dilemma: Mr. Right vs. Mr. Right Now",
        body: "Startups face a fundamental tension between hiring for current needs and hiring for future needs.\n\n**Hiring \"Mr. Right Now\" (current needs):**\n\n- Hire junior people now, add senior ones above them later\n\n- Benefits: lower burn rate (juniors are cheaper); can wait to see which early hires can \"scale\" and upgrade their skills\n\n**Hiring \"Mr. Right\" (future needs):**\n\n- Hire senior people before you need them\n\n- Benefits: seniors can hire their own teams, improving teamwork; avoids future friction where juniors feel \"displaced\" by seniors hired above them\n\n**Evolution of hiring across venture stages:**\n\n- **Startup stage:** Personal networks of core founder; young, inexperienced jacks-of-all-trades; flat structure; low cash, high equity\n\n- **Transition stage:** Impersonal searches; \"players\" transition into coaches; functional VPs hire own teams; moderate cash, lower equity with vesting\n\n- **Mature stage:** Investor networks and executive search firms; experienced A-players from large companies; pyramidal structure; high cash, stock options replace equity"
      },
      {
        title: "Investors & Board Composition",
        body: "The choice of investors shapes far more than just funding — it determines board composition, strategic guidance, and legitimacy.\n\n**Board of directors in startups:**\n\n- Early ventures: business associates and community members; few outside directors; advisory role\n\n- VC-backed startups: VCs require board representation (not necessarily proportional to equity); participatory role with significant involvement in strategic decisions\n\n**Case Study: Ockham's Financing Decision** — Two contrasting offers:\n\n- **Texas Angels:** $20M pre-money valuation, $10M capital, 50% equity sold, 3-person board (founders control 67%), no further rounds needed — but limited industry expertise\n\n- **Noro-Mosely / Monarch (VCs):** $6M pre-money valuation, $2M capital, 33.3% equity sold, 5-person board (founders control 40%), will need additional rounds — but deep industry experience and valuable contacts\n\n**How do investors add value?**\n\n- Provision of expertise\n\n- Information brokerage\n\n- Assist in recruiting senior executives\n\n- Assemble funding or achieve liquidity\n\n- **Endorsements and legitimacy** — Stuart et al. (1999) showed that biotech ventures with prominent strategic alliance partners and investors were more likely to go public, and at higher valuations\n\n> High uncertainty makes it difficult to judge a startup's true quality, so resource providers judge quality by considering the **prominence of a venture's exchange partners**. Prominent actors are more motivated and more skilled at assessing a venture's quality."
      },
      {
        title: "Founder Succession: The Rich vs. King Dilemma",
        body: "Most founders ultimately have to step down from the CEO role — and most are **forced** rather than choosing voluntarily.\n\n**Wasserman (2008)** found that by year 3, 50% of founders were no longer CEO; by year 4, only 40% remained; fewer than 25% led their companies' IPOs. Four out of five entrepreneurs are forced to step down.\n\n**The paradox of entrepreneurial success:** Most entrepreneurs view completing product development and raising venture capital as grand successes ensuring their place as CEO. The opposite is true — founder-CEOs who reach these milestones are **more likely** to be forced to step down.\n\n**The Rich vs. King framework:**\n\n- **\"Rich\" choices:** Give up more equity and control, attract better investors and executives, build a more valuable company — but lose the CEO position\n\n- **\"King\" choices:** Retain control by staying CEO and maintaining board control — but often build a less valuable company\n\n- Being both rich and king is extremely rare (the Bill Gates exception, not the rule)\n\n**Value-added of a professional CEO:**\n\n- Provides an objective view to counteract excessive founder attachment\n\n- Offers management skills for transitioning from egalitarian to centralized decision-making\n\n- Implements broader sales and marketing orientation for faster market expansion\n\n> \"Decide on three things at the start: the rules of the game, the stakes, and the quitting time.\" (Chinese proverb, cited in Wasserman, 2008)"
      },
    ],
  },
  papers: [
    {
      label: "Eesley, Hsu & Roberts (2014)",
      citation: "The Contingent Effects of Top Management Teams on Venture Performance: Aligning Founding Team Composition with Innovation Strategy and Commercialization Environment. Strategic Management Journal, 35(12), 1798–1817.",
      sections: [
        {
          title: "Core Research Question & Theory",
          body: "**Eesley, Hsu & Roberts** challenge the assumption that diverse founding teams are universally superior. They argue that optimal team composition is **contingent** on two factors: (1) the firm's **innovation strategy**, and (2) the industry **commercialization environment** (cooperative vs. competitive).\n\nThe paper builds on **Upper Echelon Theory** (Hambrick & Mason, 1984) — TMT characteristics shape organizational performance — and extends it to founding teams specifically.\n\nA key theoretical pillar is **founder imprinting** (Baron, Burton & Hannan, 1999; Stinchcombe, 1965): founding team composition has long-lived effects on organizational processes, structure, and outcomes — even decades after founders depart. This challenges the **life cycle model** (Greiner, 1972), which assumes ventures can simply add appropriate managers over time.\n\n**Commercialization environments** (Gans & Stern, 2003; Teece, 1986):\n\n- **Cooperative environments:** Strong IP protection + important complementary assets held by incumbents (e.g., biotech, medical devices, chemicals, telecom). Ventures partner with incumbents.\n\n- **Competitive environments:** Weak IP protection + low cost of assembling complementary assets (e.g., software, consumer products, web services). Ventures compete head-to-head."
        },
        {
          title: "Hypotheses & Data",
          body: "**Hypothesis 1a:** Diverse founding teams are positively associated with venture performance, but are **less beneficial** when pursuing an innovator strategy.\n\n**Hypothesis 1b:** Technically focused founding teams, when pursuing an innovation strategy, are **positively** associated with venture performance.\n\n**Hypothesis 2a:** In a **competitive** environment, diverse founding teams are positively associated with performance.\n\n**Hypothesis 2b:** In a **cooperative** environment, technology-focused founding teams are positively associated with performance.\n\n**Data:** Cross-sectional survey of **2,067 ventures** founded between 1931 and 2003, drawn from a survey of 105,928 MIT alumni (43,668 responses, 41.2% response rate). 41% of firms had failed. Matched with Compustat, USPTO, and Dun & Bradstreet data through 2006.\n\n**Dependent variable:** \"Favorable exit\" — IPO or acquisition where valuation exceeded capital raised, or firm was older than 5 years with positive revenues. 22.6% of firms achieved this.\n\n**Key independent variables:** \"Diverse team\" = count of different functional roles (1–4); \"Technically focused\" = binary, all founders in technology roles; \"Innovator\" = composite index (0–3) based on innovation importance, patent ownership, and research lab origins."
        },
        {
          title: "Key Findings",
          body: "**All four hypotheses were supported:**\n\n**H1a — Supported:** Diverse teams generally improve performance, but the interaction with innovator strategy is **negative and significant**. An additional functional role when pursuing innovation **reduces** favorable exit likelihood by **8.4%**, canceling out the general positive effect of diversity.\n\n**H1b — Supported:** Technically focused teams pursuing innovation have a **3.7% greater likelihood** of favorable exit. The interaction shows an inverse U-shape with peak effect at **7%** for moderate-probability firms.\n\n**H2a — Supported:** In competitive environments, an additional functional role yields a **7.9% increase** in favorable exit likelihood (odds ratio 1.759, p < 0.05).\n\n**H2b — Supported:** In cooperative environments, technically focused teams have a **12.8% greater likelihood** of favorable exit (odds ratio 1.760, p < 0.05).\n\n**Economic magnitude:** Using Hall & Woodward (2010) data, the 3.7% increase from a technically focused innovator team represents approximately **$185,000 additional expected value for VCs** and **$333,000 for entrepreneurs** — enough to justify headhunting costs for the right co-founder.\n\n> The findings strongly support the **imprinting view** over the life cycle view: ventures cannot ignore founding team composition and expect to later professionalize. The initial team must be aligned from the start."
        },
        {
          title: "Practical Implications",
          body: "Entrepreneurs should consider their likely commercialization strategy and industry environment **when forming their founding team**, not after.\n\n**Specific guidance:**\n\n- If entering a **competitive environment** (e.g., software, consumer products): build a **functionally diverse** founding team\n\n- If entering a **cooperative environment** (e.g., biotech, medical devices): build a **technically focused** founding team\n\n- If pursuing an **innovation strategy**: a **technically focused** team is associated with better outcomes\n\n- Do not assume you can simply \"professionalize\" later — founding team imprinting has lasting effects\n\n**Robustness:** Results hold across alternative dependent variables (any exit), alternative independent variable specifications, different time periods, and instrumental variables addressing endogeneity. Young first-time founders (under 28) and \"naive\" teams (formed via family/social channels) show consistent patterns — ruling out strategic self-selection as the sole driver.\n\n> The source of complexity matters: **technical complexity** favors focused teams; **business model complexity** favors diverse teams. One size does not fit all."
        },
      ],
    },
    {
      label: "Stuart, Hoang & Hybels (1999)",
      citation: "Interorganizational Endorsements and the Performance of Entrepreneurial Ventures. Administrative Science Quarterly, 44(2), 315–349.",
      sections: [
        {
          title: "The Endorsement Theory",
          body: "**Stuart, Hoang & Hybels** investigate how the interorganizational networks of young companies affect their ability to acquire resources for survival and growth.\n\n**Central thesis:** Faced with great uncertainty about the quality of young companies, **third parties rely on the prominence of a firm's affiliates to make quality judgments**. Young companies \"endorsed\" by prominent exchange partners perform better than otherwise comparable ventures.\n\n**Three social mechanisms drive endorsement effects:**\n\n1. **Reciprocal reputation effects:** Prominent organizations risk reputational damage from low-quality partners, so they are selective. Association with a prominent partner thus signals quality (Blau, 1964; Podolny, 1994).\n\n2. **Quality assessment / evaluative capability:** Prominent organizations are perceived as expert evaluators due to experience. A connection to such an organization is interpreted as an endorsement — they have determined the venture merits transacting (Stuart, 1998).\n\n3. **Reliability signal:** Prominent partners draw attention to the new venture, and the fact that it was selected signals reliability (Hannan & Freeman, 1984).\n\n> The authors are agnostic about whether partner prominence is actually correlated with true firm quality. They argue that **perceptions of value shaped by affiliation patterns** become self-fulfilling — being perceived as high quality is itself an extremely valuable resource."
        },
        {
          title: "Research Design: Biotechnology Industry",
          body: "**Sample:** 301 dedicated, venture-capital-backed biotechnology firms (human diagnostics and therapeutics), January 1978 – December 1991.\n\n**Why biotech?** Launched by competence-destroying innovations (recombinant DNA, 1973; hybridoma, 1975). Established pharma firms were poorly positioned; commercialization was led by startup firms. The 1980 Diamond v. Chakrabarty ruling and Genentech's explosive IPO catalyzed the industry. Biotech firms became immersed in extensive alliance networks — ideal for studying interorganizational effects.\n\n**Performance variables:**\n\n1. **Rate of IPO** — time from incorporation to initial public offering (piecewise exponential hazard model)\n\n2. **Market capitalization at IPO** — total market cap minus IPO proceeds (OLS with Heckman selection correction)\n\n**Prominence measures:**\n\n- **Commercial prominence:** An organization's normalized degree score in the network of strategic alliances (updated quarterly)\n\n- **Technological prominence:** Degree score in a patent citation network — highly cited patents represent the most important innovations\n\n- **Investment bank prestige:** Carter & Manaster (1990) scale, 0–9\n\nOf 301 firms, **121 experienced IPOs** by end of 1991; 180 were right-censored."
        },
        {
          title: "Key Findings",
          body: "**Time-to-IPO results:**\n\n- More patents → faster IPO (each patent multiplied rate by 1.11)\n\n- Each additional $10M in venture funding multiplied IPO rate by 1.16\n\n- A standard deviation increase in **commercial prominence of equity investors** multiplied IPO rate by **1.23**\n\n- **Technological prominence of equity investors** raised IPO rate by **33%**\n\n**Market valuation results:**\n\n- A standard deviation increase in **commercial prominence of alliance partners** raised predicted market value by **35%**\n\n- **Commercial prominence of equity investors** raised value by **28%**\n\n- **Investment bank prestige** raised predicted value by **45%**\n\n**Contingency effects (Hypothesis 4) — the strongest finding:**\n\n- Endorsement effects are **strongest when uncertainty is highest** — for younger firms and those with less funding\n\n- **Illustrative comparison:** Cytogen (age 6) vs. Invitron (age <3), both with nearly identical equity investor prominence. For young Invitron, the prominent investor predicted a **91% increase** in market value. For older Cytogen, less than **1% increase**.\n\n- As firms age and garner accomplishments, the endorsement effect declines precipitously\n\n> **\"Who matters more than how many\"** — the positive effects of counting alliances often dropped out once exchange-partner prominence scores were entered. The impact of interorganizational relations is driven by who you are associated with, not the volume of relations."
        },
        {
          title: "Cumulative Advantage & Implications",
          body: "**Cumulative advantage (Matthew Effect):** Firms that obtained one prominent exchange partner tended to obtain others across the board. A prominent affiliate serves as an ally, introducing the company to its associates, creating a **cumulating cycle of advantage**.\n\n**Key takeaways:**\n\n1. **Sponsorship can substitute for accomplishment:** Under high uncertainty, exchange partner prominence has much stronger effects. As firms age and develop track records, endorsement effects decline. Conversely, accomplishments take on added significance for firms lacking notable sponsors.\n\n2. **Endorsement is an ancillary but powerful byproduct of alliances:** Alliances are primarily instrumental (resource acquisition, uniting complementary assets), but they carry reputational consequences. The endorsement benefit stems from the fact that the biotech company survived due diligence by a capable evaluator.\n\n3. **Implications for startups:** Young ventures should strategically pursue relationships with **prominent partners** — not just any partners. The legitimacy and signaling value of prominent affiliates is most valuable precisely when the venture has the least to show for itself.\n\n> The underlying social process operates widely beyond biotech: in any setting where uncertainty makes quality assessment difficult, **the identity of exchange partners becomes a primary heuristic for evaluating organizational quality**."
        },
      ],
    },
    {
      label: "Wasserman (2008)",
      citation: "The Founder's Dilemma. Harvard Business Review, February 2008.",
      sections: [
        {
          title: "The Rich vs. King Trade-Off",
          body: "**Wasserman's central argument:** Entrepreneurs face a fundamental tension between two goals — **getting rich** (maximizing wealth) and **being king** (retaining control). It is extremely difficult to achieve both simultaneously.\n\nEmpirical evidence from multiple studies:\n\n- Study of **212 American start-ups**: by year 3, 50% of founders were no longer CEO; by year 4, only 40% remained; fewer than 25% led their companies' IPOs\n\n- Study of **528 new ventures**: 51% of entrepreneurs made the same or less money than at least one person reporting to them; founders received **20% less** in cash compensation than non-founders in similar roles\n\n- Arnold Cooper's study of **3,000 entrepreneurs**: founders claimed 81% average chance of success for their own venture but only 59% for similar ventures; one in three claimed 100% likelihood of success\n\n**The 2x2 framework:**\n\n- **Rich** (little control, high financial gains): Founder gives up equity and control, attracts better investors and executives, builds a more valuable company\n\n- **King** (complete control, lower financial gains): Founder retains CEO position and board control, but often builds a less valuable company\n\n- **Exception** (both rich and king): Extremely rare — the Bill Gates / Phil Knight archetype\n\n- **Failure** (neither): The worst outcome for founders who don't make a conscious choice"
        },
        {
          title: "The Paradox of Entrepreneurial Success",
          body: "As ventures grow, founders must attract outside capital, which requires giving up equity and board control. The skills needed to **start** a company (vision, product development) are fundamentally different from those needed to **scale** it (processes, formal hierarchy, marketing infrastructure, financial management).\n\n> \"The faster that founder-CEOs lead their companies to the point where they need outside funds and new management skills, the quicker they will lose management control.\"\n\nMost entrepreneurs view completing product development and raising venture capital as grand successes ensuring their place as CEO. **The opposite is true** — these milestones make founder-CEOs **more likely** to be forced to step down, while also increasing their resistance to succession.\n\nFour out of five entrepreneurs are **forced** to step down from the CEO post. Investors wield the most influence just before they invest, often using that moment to require a professional CEO.\n\n**Founders exhibit overconfidence and naivete:** These traits are necessary to launch ventures but later become liabilities. Emotional attachment, low self-pay, and identity fusion with the venture (\"my baby\") make transitions extremely difficult."
        },
        {
          title: "Case Studies: Rich and King Choices",
          body: "**Rich choices (prioritizing wealth):**\n\n- **Jim Triandiflou, Ockham Technologies:** Chose a well-known VC firm over an angel investor, giving up board control (2 of 5 seats vs. retaining control). Result: Ockham grew far more valuable.\n\n- **Lew Cirne, Wily Technology:** Gave up board and company control to Greylock Partners and other VCs. CA acquired Wily for far more than if Cirne had gone alone. However, after stepping down as CEO, Cirne was made CTO but found no one reported to him — illustrating how post-succession transitions can become contentious.\n\n- **Evan Williams, Blogger/Odeo:** Built Pyra Labs (Blogger) without outside investors, sold to Google in 2003. For his next venture (Odeo), quickly brought in VC because he believed it had more substantial potential. Later had a change of heart and bought back the company in 2006.\n\n**King choices (prioritizing control):**\n\n- **John Gabbert, Room & Board:** Repeatedly rejected funding offers that would enable faster growth, fearing loss of control. \"The trade-offs are just too great.\"\n\n- **Henry Royce (1917):** \"I prefer to be absolute boss over my own department (even if it was extremely small) rather than to be associated with a much larger technical department over which I had only joint control.\"\n\n- **Anonymous Boston IT founder:** Wanted to raise $5M but realized investors would insist on a professional CEO. Chose to raise only $2M and remained CEO for two more years."
        },
        {
          title: "Practical Implications",
          body: "**For founders motivated by wealth (\"Rich\"):**\n\n- Recognize when the top job has stretched beyond your capabilities and hire a new CEO yourself\n\n- Work with your board to develop post-succession roles\n\n- Be open to pursuing ideas that require external financing\n\n- Can make the entrepreneurial leap sooner since they won't mind taking investor money\n\n**For founders motivated by control (\"King\"):**\n\n- Restrict yourself to businesses where you already have the needed skills and contacts\n\n- Focus on businesses that don't require large amounts of capital\n\n- Consider waiting until late in your career to start a venture, allowing time to develop broader skills and accumulate savings for bootstrapping\n\n**For boards managing succession:**\n\n- \"You can replace an executive, but you can't replace a founder\" — founders can become negative forces if poorly managed\n\n- Help founders find new functional roles that leverage their strengths\n\n- The less similar the new CEO is to the founder (e.g., 10 years older), the easier the transition\n\n- **E Ink example:** Cofounder Russ Wilcox rotated through finance, product marketing, sales, and R&D after stepping down. By 2004, the board reappointed him CEO — no one more qualified could be found\n\n> \"Decide on three things at the start: the rules of the game, the stakes, and the quitting time.\" (Chinese proverb)"
        },
      ],
    },
  ],
  sideLabels: {
    lecture: [
      "Solo or Team?", "Assessing Co-Founders", "Founding with Friends",
      "Equity Splits", "Dividing Roles", "Hiring Dilemma",
      "Investors & Board", "Succession: Rich vs. King",
    ],
    paper0: [
      "Research Question & Theory", "Hypotheses & Data", "Key Findings",
      "Practical Implications",
    ],
    paper1: [
      "Endorsement Theory", "Research Design", "Key Findings",
      "Cumulative Advantage",
    ],
    paper2: [
      "Rich vs. King Trade-Off", "Paradox of Success", "Case Studies",
      "Practical Implications",
    ],
  },
});
