APP.addWeek({
  id: "w3",
  num: 3,
  title: "Entrepreneurial Success: Resources & Growth",
  lecture: {
    label: "Lecture 3 — Prof. Dr. Wouter Stam",
    date: "Feb 16, 2026",
    sections: [
      {
        title: "Motivations for Self-Employment",
        body: "Research by **Dahlqvist & Davidsson (2000)** on a large sample of Swedish new ventures found that the most common motivation for becoming self-employed is:\n\n1. **To realize my idea** (~22%) — by far the most common motivation\n\n2. **Unemployment or risk thereof** (~18%)\n\n3. **To work independently** (~16%)\n\n4. **To make money** (~11%)\n\n5. **To meet an observed market need** (~8%)\n\n> Richard Branson: \"I have never gone into any business purely to make money. If that is the sole motive, then I believe you are better off not doing it.\"\n\nThis directly contradicts the popular assumption that entrepreneurs are primarily motivated by financial gain.",
      },
      {
        title: "Stylized Facts About Growth",
        body: "Five empirical regularities about business growth that any theory must explain:\n\n1. **Fast-growth businesses are a very small proportion** of the business population — most firms never grow significantly\n\n2. **Fast-growth businesses contribute disproportionately** to job growth — a handful of high-growth firms drive the majority of net job creation\n\n3. **Fast growers are smaller and younger firms** — growth tends to concentrate in young, small businesses, not established incumbents\n\n4. **Fast growth is 'spotty'** — high-growth periods are often followed by stagnation; growth is not smooth or continuous\n\n5. **Fast-growth businesses occur in all sectors** — not just tech; growth is found in traditional and mature industries as well\n\n> These facts challenge the narrative that high-growth entrepreneurship is primarily a tech phenomenon.",
      },
      {
        title: "Four Approaches to Explain Entrepreneurial Success",
        body: "Four theoretical frameworks explain why some ventures grow while others fail:\n\n1. **Random approaches** — luck and initial resource endowments determine outcomes; the environment is inherently uncertain\n\n2. **Stage model approaches** — ventures follow predictable developmental sequences of managerial challenges that must be resolved to progress\n\n3. **Environmental approaches** — industry structure, ecological density, and legitimacy determine performance more than firm-level factors\n\n4. **Resource-based approaches** — the entrepreneur's bundle of human, social, and financial capital is the primary driver of success\n\n> No single framework is sufficient; in practice, luck, stage-appropriate management, environmental fit, and strong resources all contribute to entrepreneurial success.",
      },
      {
        title: "Random Approaches: Gambler's Ruin",
        body: "The **Gambler's Ruin** model treats running a business like playing at a roulette wheel:\n\n- Use **chips (resources)** to gamble on a successful outcome (survival/growth)\n\n- **Winning** allows you to continue; **losing** eventually means leaving the table (closing the business)\n\n- Emphasizes the role of **chance** and **initial resource endowments** (startup capital)\n\nThe model can be extended to:\n\n- **Vary wealth and access to finance** — richer players survive longer\n\n- **Some may be better gamblers** — experience improves odds\n\n- **Performance thresholds** — entrepreneurs exit if performance falls below expectations\n\n**Key predictions:**\n\n- Chance is key; the role of the entrepreneur is **downplayed**\n\n- **Smaller or undercapitalized** businesses are more likely to close\n\n- **Temporal inverted U-shape**: few closures early, rising closures in the middle, few closures among established survivors\n\n> Criticism: real-world evidence suggests that entrepreneur quality and resource deployment matter — success is not purely random.",
      },
      {
        title: "Stage Model Approaches",
        body: "**Greiner (1972)** argued that organizations evolve through predictable stages, each with a dominant management style and a crisis that must be resolved to progress:\n\n- **Stage 1 — Creativity** → crisis of **leadership** (founders must professionalize management)\n\n- **Stage 2 — Direction** → crisis of **autonomy** (centralized control becomes a bottleneck)\n\n- **Stage 3 — Delegation** → crisis of **control** (managers become too independent)\n\n- **Stage 4 — Coordination** → crisis of **red tape** (bureaucracy stifles initiative)\n\n- **Stage 5 — Collaboration** → crisis of **?** (psychological saturation)\n\nAt each stage, the **management focus, organizational structure, top management style, control system, and reward system** all change.\n\n> \"As an early startup, having a group of equal partners with divergent views is a good thing. When the time comes to act fast, the best thing is to have a dictatorship. Making the transition at the right time is the elusive challenge.\" (Wasserman, 2012)\n\n**Key issues:** Stage models assume one-size-fits-all, treat growth as unidirectional, and have limited empirical reliability.",
      },
      {
        title: "Environmental Approaches & Legitimacy",
        body: "**Population ecology** (Hannan & Freeman) focuses on organic changes at the population level — the birth, growth, and death of entire industries:\n\n- **Early in an industry's lifecycle**, resources are abundant and small firms can grow fast (\"sunrise industries\")\n\n- As competition intensifies, resources become **scarce** and growth slows\n\n- **Sectoral evidence is mixed**: fast growth occurs in both 'sunrise' and traditional industries\n\n**Legitimacy** is a critical environmental resource:\n\n- **Cognitive legitimation** — how well-understood a new venture form is (taken-for-granted-ness)\n\n- **Sociopolitical legitimation** — acceptance by key stakeholders given existing norms and laws\n\n**Ways to acquire legitimacy:**\n\n- **Appear similar** to established firms (name, location, office, language)\n\n- **Show credibility** (prior accomplishments, customer testimonials, regulatory compliance)\n\n- **Associate with legitimate entities** (prestigious customers, accelerators, company directors)\n\n**Regional clusters** (Marshall, 1890): benefits include specialist labour pools, lower transport costs, and knowledge spillovers — but competition in a cluster can also eliminate growth potential.",
      },
      {
        title: "Resource-Based Approaches",
        body: "The **Resource-Based View (RBV)** is grounded in **Rumelt's (1991)** finding that what a business *does* is more important to its performance than external conditions.\n\nCore premises:\n\n- Businesses are **bundles of resources** — tangible and intangible\n\n- Resources are **heterogeneous and idiosyncratic** — differ across firms\n\n- Resources are **immobile** and **path dependent** — hard to replicate\n\n**Strategic resources** have **VRIN attributes**: Valuable, Rare, Imperfectly Immobile, Non-substitutable.\n\n> Growing businesses possess VRIN resources. But more important than owning resources are the **capabilities** to structure, bundle, and leverage them for competitive advantage.\n\nThree types of resources enable successful entrepreneurs:\n\n1. **Human capital** — knowledge, skills, and abilities\n\n2. **Social capital** — resources accessible through social connections\n\n3. **Financial capital** — funding to sustain and grow the venture\n\n**Key criticisms:** tautological (success proves resources were strategic), neglects environmental forces, and may overstate how much agency entrepreneurs really have.",
      },
      {
        title: "Human Capital: Generalists vs. Specialists",
        body: "A central question: do entrepreneurs succeed because they are **jacks-of-all-trades** or because they are **deep domain specialists**?\n\n**Generalists (Lazear, 2004):**\n\n- Entrepreneurs must perform **many tasks** simultaneously — cooking, financing, marketing, hiring, bookkeeping\n\n- Entrepreneurial income is bounded by the **weakest skill** (min function), unlike employees whose income comes from their strongest skill (max function)\n\n- Stanford MBA data: future entrepreneurs studied a **more varied curriculum** than future employees\n\n- Most entrepreneurs have **nontechnical backgrounds** and launch businesses in nontechnical industries\n\n**Specialists (Gofman & Jin, 2024):**\n\n- For **AI startups**, specialized higher education matters critically\n\n- The departure of AI professors reduces both startup formation and VC funding\n\n- AI entrepreneurs are more likely to hold **PhDs** and **CS/STEM** degrees than non-AI IT entrepreneurs\n\n> The two views are complementary: **most entrepreneurs must be generalists**, but in knowledge-intensive fields like AI, **deep domain expertise becomes a necessary foundation** that the general management layer is built upon.",
      },
      {
        title: "Social Capital & Networks",
        body: "**Social capital** is the ability to extract benefits from social structures, networks, and memberships.\n\nTwo key dimensions:\n\n- **Bonding social capital** (strong ties) — tight family and friend networks that provide trust, consistent resource access, and tacit knowledge transfer\n\n- **Bridging social capital** (weak ties) — looser organizational and professional networks that provide novel information and access to diverse resources\n\nNetwork roles matter:\n\n- **Central Connector** — highly connected within a cluster\n\n- **Information Broker** — bridges otherwise disconnected groups\n\n- **Peripheral Specialist** — deep expertise, fewer connections\n\nThe **Search–Transfer Problem** (Hansen, 1999): strong ties facilitate knowledge transfer but limit search; weak ties enable broad search but make transferring tacit knowledge difficult.\n\n**Davidsson & Honig (2003)** found:\n\n- Bonding SC predicts **entry** into nascent entrepreneurship\n\n- Bridging SC (especially **business network membership**) is the strongest predictor of **first sales and profitability**\n\n- Business network membership increased the odds of a first sale by a **factor of 4**\n\n> Successful entrepreneurship is a **social game**: human capital facilitates discovery, but social capital provides the relational infrastructure that turns discovery into viable business outcomes.",
      },
      {
        title: "Financial Capital: Angels, VCs & Crowdfunding",
        body: "Funding sources evolve as a venture matures through the **startup financing cycle**:\n\n- **Valley of Death** — personal savings, Friends, Family & Fools (FFF), seed capital\n\n- **Early stage** — Business Angels ($10K–$500K); focus on seed; faster decisions (weeks); motivated by financial returns, mentoring, and intellectual challenge\n\n- **Growth stage** — Venture Capital; focuses on high-growth ventures; extensive due diligence (months); VCs add value through expertise, information brokerage, endorsements, recruiting, and assembling funding\n\n- **Later stage** — Mezzanine, IPO, secondary offerings\n\n**VC follows a Power Law** distribution: a small number of outlier companies generate most returns; portfolio size must be large enough to capture these outliers.\n\n**Crowdfunding** (Mollick, 2013): drawing small contributions from many individuals online without standard financial intermediaries. Benefits: rapid capital access, market validation, visibility, and diverse feedback.\n\n**Evidence on windfall gains** (Andersen & Nielsen, 2012): entrepreneurs who receive unexpected inheritance windfalls perform **significantly worse** (survival, profits, income) than those who entered entrepreneurship without this push — suggesting that **ability constraints** matter more than financial constraints.\n\n> **Bootstrapping** — reducing burn rate, retaining autonomy and ownership — is often preferable to premature external funding. Resource constraints often drive creativity.",
      },
    ],
  },
  papers: [
    {
      label: "Lazear (2004)",
      citation: "Balanced Skills and Entrepreneurship. American Economic Review, 94(2), 208–211.",
      sections: [
        {
          title: "The Jack-of-All-Trades Theory",
          body: "**Lazear's central thesis** is that entrepreneurs are generalists who require a balanced set of skills across many domains, rather than deep expertise in one area.\n\nThe key intuition is a **weakest-link** production function:\n\n- **Employees/specialists** earn based on their strongest skill: income = max[x₁, x₂]\n\n- **Entrepreneurs** are limited by their weakest skill: income = λ·min[x₁, x₂]\n\nConsider the founder of a restaurant. Being a great cook is **insufficient** — the founder must also obtain funding, hire workers, choose location and décor, source supplies, keep books, and market the business. Even if tasks are outsourced, the entrepreneur needs basic knowledge in each domain to make good vendor decisions.\n\n> This view contradicts the intuition that entrepreneurs are technical specialists who launch ventures based on innovation. Data strongly reject that view. Most entrepreneurs are non-technical people forming businesses in non-technical fields.",
        },
        {
          title: "Implications of the Production Function",
          body: "The specialist vs. entrepreneur production functions have direct implications for **human capital investment strategies**:\n\n**Specialists** invest only in their strongest skill — there is no return to improving a skill that will not be used in employment.\n\n**Aspiring entrepreneurs** should invest in their weakest skills first, because that is what constrains their entrepreneurial income. Three scenarios:\n\n- If the marginal cost of improving the weak skill is very high relative to the entrepreneurial premium (λ), **no investment** is made — the individual behaves like a specialist\n\n- If costs are moderate, the entrepreneur **invests only in the weak skill** — still looks like a specialist but focusing on the weaker area\n\n- If costs are low enough, the entrepreneur invests in the weak skill until it equals the strong skill, then **raises both together** — this is the uniquely entrepreneurial investment pattern\n\n> Only entrepreneurs optimally invest in **more than one skill simultaneously**. This means aspiring entrepreneurs should have a **more balanced investment profile** than those who end up as employees.",
        },
        {
          title: "Empirical Evidence: The SPECIAL Variable",
          body: "**Lazear tests the theory** using two primary data sources:\n\n**2002 Current Population Survey (CPS):**\n\n- Entrepreneurs (incorporated self-employed) are found primarily in **nontechnical occupations**: executives/administrative (33%), supervisors/sales (12%), construction trades (6%)\n\n- They cluster in **nontechnical industries**: construction (13%), retail trade (13%), professional services (11%), business services (8%)\n\n- This is **inconsistent** with the popular image of entrepreneurs as tech innovators\n\n**Stanford MBA Alumni Survey (~5,000 respondents):**\n\n- Transcripts matched with career histories\n\n- Constructed **SPECIAL** = (courses in specialty field) − (average courses in other fields); higher SPECIAL = more specialized curriculum\n\n- Key finding: the SPECIAL score of future entrepreneurs (**2.35**) was significantly lower than for non-entrepreneurs (**2.51**)\n\n- **Logit results**: a one-standard-deviation decrease in SPECIAL increased the probability of ever being an entrepreneur by about **3 percentage points** (~one-eighth of the base rate)\n\n> Future entrepreneurs deliberately chose a **more varied curriculum** — consistent with the prediction that human capital investment reflects anticipated career choice.",
        },
        {
          title: "Implications",
          body: "> Entrepreneurs should be **good at many things**, not necessarily expert at any single one.\n\n**For would-be entrepreneurs:**\n\n- Seek work experiences and training that build breadth, not just depth\n\n- Deliberately invest in skills where you are **currently weakest** — these are the binding constraints on entrepreneurial success\n\n- Prior work in a variety of roles within a firm is consistent with entrepreneurial preparation\n\n**For business education:**\n\n- A diversified curriculum — spanning finance, marketing, operations, and strategy — is directly aligned with entrepreneurial success\n\n- Specializing too early may improve employee prospects but reduce entrepreneurial potential\n\n**Important caveat (Gofman & Jin, 2024):** Lazear's finding cannot be generalized to all academic disciplines. In AI entrepreneurship specifically, **specialized domain knowledge** acquired through advanced education is a critical success factor — even though the general entrepreneurial management skills still matter.",
        },
      ],
    },
    {
      label: "Gofman & Jin (2024)",
      citation: "Artificial Intelligence, Education, and Entrepreneurship. Journal of Finance, Forthcoming. https://doi.org/10.1111/jofi.13302",
      sections: [
        {
          title: "The AI Brain Drain",
          body: "**Gofman & Jin** document an unprecedented exodus of AI professors from North American universities to industry between 2004 and 2018.\n\nKey facts about the brain drain:\n\n- **211 full or partial departures** of tenure-track or tenured AI faculty over 2004–2018\n\n- **149 professors** took industry jobs (Google/DeepMind: 22, Amazon: 16, Microsoft: 12, NVIDIA: 7, Uber: 6, Apple: 4...)\n\n- **62 professors** established their own AI startups\n\n- By 2018, departing professors accounted for **~19% of all citations** by AI faculty at their universities — the brain drain increasingly removes the most influential researchers\n\n**Why do professors leave?**\n\n- Vastly superior **compensation** — top AI researchers can earn $1M+ at industry labs\n\n- Access to superior **computational resources, data, and scale**\n\n- As Yoshua Bengio (Turing Award winner) noted: universities \"could never match the salaries being paid in the private sector\"\n\n> CMU lost the most AI faculty (16 tenured, 0 untenured); UC Berkeley and U. Washington were also heavily affected. **43% of departing professors** were deep-learning specialists — the most cutting-edge and commercially valuable subfield.",
        },
        {
          title: "AI Entrepreneurs vs. Non-AI Entrepreneurs",
          body: "The paper compares **504 AI entrepreneurs** with **1,531 non-AI (IT) entrepreneurs** who graduated from 84 North American universities between 2010 and 2018.\n\nAI entrepreneurs are strikingly different from other IT entrepreneurs:\n\n- **25% hold a PhD** (vs. 9% of non-AI IT entrepreneurs)\n\n- **34% have a non-MBA master's degree** (vs. 26%)\n\n- Only **5% have an MBA** (vs. 8%) — suggesting **general management skills are less critical** than domain-specific knowledge\n\n- **31% studied CS** (vs. 23%)\n\n- **18% graduated from a top-10 CS department** (vs. 7%)\n\n**AI startups** also differ structurally:\n\n- Raise on average **$8.32M** in early-stage financing — $3.54M more than non-AI IT startups\n\n- Are more likely to have **PhD co-founders**\n\n- **Professor-founded AI startups** raise an average of **$23M** in under two years; 20% are acquired within 3.5 years\n\n> The education gradient in AI startup funding is **monotonic**: bachelor's ($9.25M Series-A) < master's ($12.36M) < PhD ($16.11M) < professor ($19.78M). Academic knowledge directly translates into investor confidence.",
        },
        {
          title: "Brain Drain Effects on Startup Formation and Funding",
          body: "**Extensive margin** (startup formation): when tenured AI professors depart a university 4–6 years before students' graduation (Period 1), students are significantly less likely to become AI entrepreneurs.\n\n- A one-standard-deviation increase in the tenured AI brain-drain measure during [t−6, t−4] is associated with a **~5% decline** in the number of future AI entrepreneurs graduating in year t\n\n- Departures during [t−3, t−1] (Period 2 — while students are enrolled) show a **smaller or insignificant** effect — some knowledge transfer can still occur during overlap\n\n- **Untenured faculty departures** have no significant effect — they are less likely to supervise advanced students and may leave involuntarily\n\n**Intensive margin** (fundraising): the same brain-drain measure predicts **less early-stage funding**:\n\n- A one-standard-deviation increase in tenured brain drain [t−6, t−4] → **~20% drop** in early-stage AI startup funding — about **$1.66M below the sample mean**\n\n- The effect is **absent for non-AI (IT) startups** from the same universities — ruling out city-level or university-level shocks as alternative explanations\n\n> The AI brain drain **does not affect** non-AI startup formation, incoming PhD student quality (fellowship recipients), or students' propensity to stay local — pointing clearly to the **knowledge transfer channel**.",
        },
        {
          title: "The Knowledge Transfer Channel",
          body: "The dominant explanation for the brain drain's effect is that **AI professors are irreplaceable sources of specialized knowledge** that students convert into entrepreneurial capability.\n\nEvidence supporting the knowledge transfer channel:\n\n- The negative effect is **strongest for departures prior to students' enrollment** — confirming that direct faculty–student interaction is the mechanism\n\n- **Deep-learning professor** departures have disproportionately larger effects than non-deep-learning departures — the most advanced, cutting-edge knowledge matters most\n\n- The effect is concentrated among **master's and PhD students**, not undergraduates — consistent with advanced knowledge transfer, not just leadership or networking skills\n\n- Departures from **top-10 CS departments** have a significantly larger negative interaction effect — the best professors at the best schools transfer the most valuable knowledge\n\n> Specialized AI knowledge provides students with three things: the technical ability to **implement startup ideas**, the ability to **evaluate AI talent** when hiring, and the **credibility** that attracts venture capital. General management skills (VRIN) alone are insufficient.\n\n**Policy implication:** Big-tech firms' poaching of AI professors creates an **entrepreneurship externality** — it reduces knowledge spillovers from universities to future founders, potentially slowing AI-driven innovation and growth.",
        },
      ],
    },
    {
      label: "Davidsson & Honig (2003)",
      citation: "The Role of Social and Human Capital Among Nascent Entrepreneurs. Journal of Business Venturing, 18(3), 301–331.",
      sections: [
        {
          title: "Research Design & Methodology",
          body: "**Davidsson & Honig** conducted a landmark **longitudinal study** of Swedish nascent entrepreneurs — those currently attempting to start a business, captured before the firm is officially established.\n\nThe design overcomes two major methodological weaknesses in prior entrepreneurship research:\n\n- **Success bias** — studying only existing firms excludes the ~50% of attempts that never result in a registered business\n\n- **Hindsight bias** — asking founders to recall their start-up process retrospectively distorts memory and rationalizes outcomes\n\n**Sample:**\n\n- Screened 30,427 Swedish adults via telephone interview\n\n- Identified **380 verified nascent entrepreneurs** (actively taking at least one gestation step toward starting a new independent firm)\n\n- Matched with a **control group of 608 non-entrepreneurs** from the same population\n\n- Followed nascent entrepreneurs for **18 months** with surveys at 6, 12, and 18 months\n\n**Dependent variables** studied:\n\n1. **Discovery** — probability of being a nascent entrepreneur vs. control\n\n2. **Gestation activity** — number of start-up steps completed (up to 46 sequences across 20 activities)\n\n3. **First sale** — receiving any revenue during the study period\n\n4. **Profitability** — reporting a profit at any follow-up wave",
        },
        {
          title: "Human Capital Findings",
          body: "**Human capital theory** predicts that knowledge improves both the detection and exploitation of entrepreneurial opportunities.\n\n**Discovery stage** (nascent vs. control group):\n\n- **Years of formal education** significantly increases the probability of being a nascent entrepreneur (factor of 1.18 per additional year)\n\n- **Work experience** has a small positive effect\n\n- **Previous start-up experience** is the strongest human capital predictor (factor of 2.17) → **Hypothesis 1 supported**\n\n**Exploitation stage** (performance among nascent entrepreneurs):\n\n- **Taking business classes** increased the frequency of gestation activities — but NOT first sales or profitability\n\n- **Previous start-up experience** also predicted gestation pace — but NOT first sales or profitability\n\n- **Formal education, management experience, and general work experience** had NO significant effect on exploitation outcomes\n\n> **Hypothesis 3 not supported**: no human capital variable predicted first sales or profitability.\n\n**Key insight:** Human capital matters for **discovery** (who attempts entrepreneurship) but not for **successful completion** of the start-up process. As the process unfolds, increasingly specific and idiosyncratic resources are required — resources that general human capital cannot provide.\n\n> Even business classes, the most task-specific form of education studied, only increased bureaucratic gestation activities but failed to improve market outcomes.",
        },
        {
          title: "Social Capital Findings",
          body: "Social capital proved to be a **more consistent and powerful** predictor of entrepreneurial outcomes than human capital at every stage of the process.\n\n**Discovery stage** (bonding social capital):\n\n- **Parents in business** increased odds of being a nascent entrepreneur by a factor of **1.4**\n\n- **Encouragement from friends/family** increased odds by a factor of **1.9**\n\n- **Close friends or neighbors in business** doubled the odds (**factor of 2.0**)\n\n→ **Hypothesis 4 strongly supported**\n\n**Exploitation — gestation pace** (bridging social capital becomes dominant):\n\n- **Member of a business network** had the strongest coefficient in the entire equation (13.23 additional gestation sequences over 18 months)\n\n- Being a **member of a start-up team** significantly increased pace\n\n- **Family and friend encouragement** also significantly predicted gestation pace\n\n→ **Hypothesis 5 strongly supported**\n\n**Exploitation — first sales and profitability:**\n\n- **Member of a business network** increased the odds of a first sale by a factor of **4.34** and was the strongest predictor of profitability\n\n- No other human capital or social capital variable consistently predicted these hard outcomes\n\n→ **Hypothesis 6 partially supported** — only business network membership reliably predicted success\n\n> Unexpectedly, **contact with assistance agencies** predicted more gestation activities at entry but had **no effect** on sales or profitability — suggesting these agencies promote bureaucratic compliance rather than market-relevant activity.",
        },
        {
          title: "Key Patterns & Implications",
          body: "Three overarching patterns emerge from the study:\n\n1. **Social capital overtakes human capital as the process advances.** Bonding social capital (who you know intimately) predicts discovery; bridging social capital (who you know professionally) increasingly determines exploitation success. Successful entrepreneurship is a **social game**.\n\n2. **Resources become more specific as the process progresses.** General human capital (years of education, any work experience) is influential early but becomes irrelevant by the time of first sales. Success at the exploitation stage requires **idiosyncratic, context-specific** knowledge that generalist models cannot predict.\n\n3. **Formal support programs are largely ineffective at the market outcomes level.** Business classes and agency contact increase activity (gestation sequences) but fail to predict sales or profits — suggesting they may teach the wrong things or address the wrong bottlenecks.\n\n**Practical implications:**\n\n- **Entrepreneurs** should invest actively in **business network memberships** (Chambers of Commerce, trade associations, professional groups) — these provide the bridging ties most consistently linked to first sales\n\n- **Policy makers** should shift focus from **training programs** to **structural networking infrastructure** — incubators, mentoring programs, and community networks\n\n- **Established firms** seeking intrapreneurship should develop **bridging social capital** within their organizational structures to facilitate knowledge search and new opportunity exploitation\n\n> \"Apparently, while human capital factors can explain discovery and, to some extent, progression of the exploitation process, it is only when applied within the context of a relevant social structure that such qualities can help achieve successful outcomes.\"",
        },
      ],
    },
  ],
  sideLabels: {
    lecture: [
      "Motivations for Self-Employment", "Stylized Facts About Growth", "Four Approaches",
      "Random: Gambler's Ruin", "Stage Model Approaches", "Environmental & Legitimacy",
      "Resource-Based Approaches", "Human Capital: Generalists vs. Specialists",
      "Social Capital & Networks", "Financial Capital",
    ],
    paper0: [
      "Jack-of-All-Trades Theory", "Investment Implications", "Empirical Evidence",
      "Implications",
    ],
    paper1: [
      "The AI Brain Drain", "AI vs. Non-AI Entrepreneurs", "Formation & Funding Effects",
      "Knowledge Transfer Channel",
    ],
    paper2: [
      "Research Design", "Human Capital Findings", "Social Capital Findings",
      "Key Patterns & Implications",
    ],
  },
});
