APP.addWeek({
  id: "w5",
  num: 5,
  title: "Defining & Validating the Business Model",
  lecture: {
    label: "Lecture 5 — Prof. Dr. Wouter Stam",
    date: "Mar 2, 2026",
    sections: [
      {
        title: "The Entrepreneurial Process & Business Models",
        body: "The entrepreneurial process unfolds through four key stages: **opportunity recognition & evaluation** → **mobilizing resources** → **defining & validating the business model** → **managing & growing the venture**.\n\nA **business model** describes how a venture creates, delivers, and captures value. It answers four fundamental questions:\n\n- **WHAT** value do you create? (value proposition)\n- **WHO** do you create it for? (customer segments)\n- **HOW** do you create and deliver it? (key resources, activities, partners, channels)\n- **Revenue model** — how does the venture capture value and generate income?\n\n> **Critical distinction:** A business model is NOT the same as a revenue model. The revenue model is only one component of the broader business model — it describes how the firm earns money, not how it creates or delivers value.\n\nEntrepreneurs must design all four dimensions coherently. A flawed assumption in any one of them can cause the entire venture to fail."
      },
      {
        title: "Business Model Canvas",
        body: "The **Business Model Canvas** (Osterwalder & Pigneur) organizes a business model into 9 building blocks:\n\n**Feasibility (left side — how?):**\n\n- Key Partners\n- Key Activities\n- Key Resources\n\n**Desirability (right side — who & what?):**\n\n- Customer Segments\n- Customer Relationships\n- Channels\n- Value Propositions (center)\n\n**Viability (bottom — revenue model):**\n\n- Cost Structure\n- Revenue Streams\n\nThe BMC provides a one-page visual overview of the business model and is useful for identifying assumptions, gaps, and interdependencies across the nine blocks.\n\n> **Warning:** The BMC is not just a revenue model. Entrepreneurs who treat it as only a financial or monetization tool miss the full picture. All nine blocks must be addressed."
      },
      {
        title: "Validating Assumptions: Why It Matters",
        body: "Every business model rests on assumptions. If those assumptions are wrong, the venture fails — regardless of how much capital was raised.\n\n**Case Study: AirBnb** — The central assumption was that strangers would be willing to sleep in other strangers' homes. This seemed absurd at the time but was validated through testing.\n\n**Case Study: Van Moof (bankrupt 2023)** — Raised €180M. The false assumption: that the company could scale globally without building out a robust service and repair infrastructure. When bikes broke down, customers couldn't get them fixed, destroying retention and trust.\n\n**Case Study: Pieter Pot (bankrupt December 2023)** — Raised €12M. Sold groceries in reusable glass jars to reduce plastic waste. The false assumption: that customers would reliably return the jars. In practice, return rates were far too low to make the economics work.\n\n> The common thread in all three cases: **a single false assumption, if left untested, can sink an entire venture.** The question is not whether your model has assumptions — it always does. The question is whether you identify and test them before running out of money.\n\n**Key implication:** The earlier you identify and test your most critical assumptions, the lower the cost of being wrong."
      },
      {
        title: "The Business Plan Debate",
        body: "Should entrepreneurs write a formal business plan? There is genuine debate.\n\n**The hockey-stick curve** — A typical venture cash flow projection shows:\n\n- **Burn rate:** Cash consumed per period before revenues cover costs\n- **Time to first positive cash flow:** When monthly revenues first exceed monthly costs\n- **Breakeven point:** When cumulative revenues cover cumulative costs\n- **Maximum financing needs:** The trough before the curve turns positive\n\n**Benefits of bootstrapping** (avoiding external funding):\n\n- Retain full equity and control\n- No investor pressure or board oversight\n- Forces capital efficiency and creative problem-solving\n- Reduces risk of founder displacement\n\nA **Wall Street Journal** article debate highlights conflicting views: some argue business plans are wasteful exercises in fiction; others argue the discipline of planning forces founders to pressure-test assumptions and identify key unknowns.\n\n**The Sahlman Framework** offers a middle ground — focus a business plan on four elements:\n\n- **People** — Who are the founders and key team members? Do they have relevant experience?\n- **Opportunity** — What is the market, how large is it, and how fast is it growing?\n- **Context** — What macro forces (regulatory, economic, technological) shape the opportunity?\n- **Risk & Reward** — What are the key risks? What is the potential upside if things go right?\n\n> This framework shifts the focus from financial projections to the underlying drivers of success and failure."
      },
      {
        title: "Hypothesis-Driven Entrepreneurship & MVP",
        body: "**Hypothesis-driven entrepreneurship** (rooted in the Lean Startup methodology) treats the venture as a series of experiments.\n\n**The 7-step cycle:**\n\n1. **Envision** the business model\n2. **Identify** the key assumptions (leap-of-faith assumptions)\n3. **Build** a minimum viable product (MVP)\n4. **Measure** customer response\n5. **Analyze** the data\n6. **Learn** what the data means\n7. **Decide:** persevere (assumption confirmed), pivot (change direction), or perish (abandon)\n\n> **Falsifiability is essential:** \"If you cannot fail, you cannot learn.\" An experiment that can only confirm your hypothesis is not a real experiment. Define success criteria in advance.\n\n**Types of MVPs:**\n\n- **Constrained product functionality** — A stripped-down version of the product that tests the core value proposition (e.g., Dropbox's explainer video before the product existed)\n- **Constrained operational capability** — The full experience delivered manually or at small scale to test desirability before building full infrastructure\n\n**Example — Dropbox:** Before building the product, Drew Houston created a short demo video explaining the concept. Sign-ups surged overnight, validating demand before a line of production code was written.\n\n**False positives vs. false negatives in MVP testing:**\n\n- **False positive:** MVP signals success but the real product fails (e.g., early adopters ≠ mainstream market)\n- **False negative:** MVP signals failure but the real product would have succeeded (e.g., MVP is too rough to be representative)\n\n**Example — Dyme (Dutch fintech):** Tested 4 core hypotheses across 3 landing-page experiments before building the app, using click-through rates and sign-up behavior to validate demand for each feature."
      },
      {
        title: "Zipcar Case: Business Model & Investor Assessment",
        body: "**Zipcar** (founded 1999 by Robin Chase and Antje Danielson) pioneered urban car-sharing. Members pay a monthly fee plus hourly/per-mile rates to access a shared fleet — no ownership, no insurance hassle.\n\n**Zipcar's vision:** \"To provide the freedom of a car without the costs and hassles of ownership.\"\n\n**Applying the Sahlman framework to assess Zipcar as an investment:**\n\n**People:**\n- Both founders are well-educated (Harvard, MIT)\n- Limited direct experience in the car industry or building startups\n- Danielson was not fully committed — retained her other job; she and Chase had a roughly 50/50 equity split despite this imbalance in commitment\n\n**Opportunity:**\n- Projected pretax profit of ~$1.05M per city at maturity\n- Model targets 15 cities → ~$16M total pretax profit\n- Large addressable market: urban residents who want car access without ownership\n- Favorable macro trends: urbanization, environmental awareness, rising car costs\n\n**Context:**\n- Limited competition at the time of founding (car-sharing was new in the US)\n- Regulatory environment generally supportive\n- Technology (internet, GPS) enabling new coordination models\n\n**Risk & Reward:**\n- Key risks: utilization assumptions, member behavior, car fleet costs, operational complexity\n- Reward: first-mover advantage in a potentially large market\n\n> Overall assessment: Strong opportunity and favorable context, but team concerns (commitment imbalance, limited industry experience) and unvalidated assumptions about utilization and member behavior represent significant risk."
      },
      {
        title: "Zipcar Fishbone Analysis",
        body: "The **fishbone (or driver tree) analysis** deconstructs the business model into its key financial drivers — making assumptions explicit and testable.\n\n**Zipcar's \"blended model\"** combines two views:\n\n- **Per-car cost view** — What does it cost to put one car on the street?\n- **Per-member revenue view** — What revenue does one member generate?\n\n**The 18 members/car assumption:**\n\n`40% utilization × 24 hrs × 30 days = 288 hrs/car/month`\n`288 hrs ÷ 16 hrs/member/month = 18 members per car`\n\n**May 2000 plan vs. September 2000 actuals:**\n\n- Utilization: **40%** planned → **30.6%** actual\n- Uses per month per member: **4** planned → **1.98** actual\n- Hours per use: **4** planned → **9.62** actual\n- $/hour charged: **$5.50** planned → **$3.84** actual\n- Miles per use: **22** planned → **48.8** actual\n- $/mile charged: **$0.40** planned → **$0.14** actual\n- Members per car: **18** planned → **11.6** actual\n- Contribution margin/member: **$90.26** planned → **$26.51** actual\n- Total contribution margin: significantly lower than projected\n\n> **Key insight:** Multiple assumptions were wrong simultaneously, and in the same direction. The members were using cars differently than expected — fewer trips but longer duration and distance — which broke the revenue-per-member model while keeping costs constant.\n\nThe fishbone analysis reveals *which* assumptions drove the gap and allows founders and investors to ask: can these be corrected with operational changes, or do they reflect a fundamental flaw in the model?"
      },
      {
        title: "Conclusions & Key Steps",
        body: "**Core takeaways from Week 5:**\n\n- A **business model is not a financial projection** — it is a theory of how the venture creates, delivers, and captures value\n- Use the **fishbone analysis** to dissect your business model into its constituent assumptions\n- **Focus on key drivers** — not all assumptions are equally important; identify the ones that most affect viability\n- **Test early and cheaply** — the cost of a wrong assumption grows exponentially as you scale\n\n**5-step process for validating your business model:**\n\n1. **Identify revenue streams** — How does the venture make money?\n2. **Build the fishbone** — What are all the drivers of revenue and cost?\n3. **Create an assumptions sheet** — List every assumption, rate its importance and uncertainty\n4. **Test your hypotheses** — Design MVPs and experiments targeting your highest-risk assumptions\n5. **Develop the business plan** — Only after key assumptions are validated, build the full plan\n\n> The goal is not to eliminate uncertainty — it never fully disappears. The goal is to **reduce the most dangerous uncertainties** as early and cheaply as possible, so that capital is deployed on validated foundations rather than untested hope."
      },
    ],
  },
  papers: [
    {
      label: "Sahlman (1997)",
      citation: "Sahlman, W. A. (1997). How to Write a Great Business Plan. Harvard Business Review, 75(4), 98–108.",
      sections: [
        {
          title: "The Framework: People, Opportunity, Context, Risk & Reward",
          body: "Sahlman argues that most business plans waste too much ink on financial projections and too little on what actually determines success or failure. He proposes a framework built around four interdependent factors:\n\n- **People** — Who are the founders and management team? What have they accomplished before? What is their relevant experience? Do they know their own limitations? Are they honest?\n\n- **Opportunity** — What is the business model? How large is the market? How fast is it growing? Is entry into the market easy or difficult? Can the venture achieve and sustain a competitive advantage?\n\n- **Context** — What macro environment does the business operate in? What regulatory, technological, and economic forces shape the opportunity? Context can be favorable or unfavorable and changes over time.\n\n- **Risk & Reward** — What can go wrong, and what will the team do if it does? What is the potential upside? Is the risk/reward tradeoff compelling for investors?\n\n> \"All the information, all the analysis, all the conclusions come down to how much risk the business actually faces and what the potential rewards are.\" — Sahlman (1997)\n\nThese four factors are deeply interconnected. A great opportunity with a weak team is likely to fail. A strong team in a terrible market is still a bad bet."
        },
        {
          title: "People",
          body: "Sahlman places people first — and argues they matter most. Experienced investors often say they would rather back an **A-team with a B-idea** than a B-team with an A-idea.\n\n**What to look for in the team:**\n\n- Relevant skills and experience — have they done something similar before?\n- Demonstrated ability to execute under pressure and ambiguity\n- Self-awareness — do they know what they don't know?\n- Complementary skills across the team\n- Commitment and resilience — will they stay when things get hard?\n- Integrity — are they honest with investors and with themselves?\n\n**Red flags:**\n\n- Founders with no relevant industry experience claiming they will learn on the fly\n- Teams where everyone has the same background (no complementarity)\n- Founders who are not fully committed (keeping a day job, 50/50 split despite unequal involvement)\n- Overconfidence masking lack of preparation\n\n> The best teams have **already demonstrated** the relevant capabilities — not just claimed them. Look for evidence of past performance in analogous situations."
        },
        {
          title: "Opportunity",
          body: "A great business plan starts with a large, growing market with real customer pain. Sahlman identifies key questions any serious investor will ask:\n\n- **How large is the market?** Total addressable market (TAM) must be big enough to justify investment\n- **How fast is it growing?** Fast-growing markets forgive mistakes; slow-growing markets punish them\n- **What is the competitive intensity?** Low barriers to entry attract competition; high barriers enable margins\n- **What is the venture's competitive advantage?** Is it durable or easily copied?\n- **What does the unit economics look like?** Can the business make money on each transaction?\n\n**Business model clarity:**\n\n- How does the venture make money? (revenue model)\n- Who are the customers and why will they buy?\n- What is the cost structure and path to profitability?\n\n> \"I want to see a business where the fundamentals make sense — where there's a real customer who will actually pay real money for something they genuinely need or want.\" — Sahlman (1997)\n\nOpportunities are not static — they open and close. Timing matters enormously. A venture launched too early or too late relative to market readiness can fail even with a sound model."
        },
        {
          title: "Context",
          body: "Context is the macro environment in which the business operates. Unlike people and opportunity, **context is largely outside the entrepreneur's control** — but it profoundly shapes the venture's prospects.\n\n**Key contextual factors:**\n\n- **Regulatory environment** — Is the industry regulated? Are regulations favorable, changing, or a barrier?\n- **Technology trends** — Does technology enable the business model, or is it a threat?\n- **Economic conditions** — Interest rates, consumer confidence, capital availability\n- **Social and demographic trends** — Is the target market growing or shrinking?\n- **Competitive dynamics** — Are incumbents weak or strong? Are substitutes available?\n\n**Why context matters for investors:**\n\n- A good idea in a bad context often fails\n- Context can change rapidly, turning a bad situation good (or vice versa)\n- Entrepreneurs who understand the context can time their entry and pivot in response to change\n\n> **Critical implication:** Business plans should explicitly address the context and show that the team understands both the tailwinds and headwinds. Plans that ignore context signal naive overconfidence."
        },
        {
          title: "Risk & Reward and the Deal",
          body: "The final element of the Sahlman framework forces an honest accounting of downside risks and upside potential.\n\n**Risk analysis — what can go wrong?**\n\n- Market risk: customers don't want the product\n- Technology risk: the product can't be built as envisioned\n- Execution risk: the team can't deliver\n- Financial risk: cash runs out before breakeven\n- Competitive risk: a larger player enters and copies the model\n- Regulatory risk: government changes the rules\n\n**For each major risk, a strong business plan should:**\n\n1. Acknowledge the risk honestly\n2. Explain what the team will do if it materializes\n3. Show that the team has thought through contingencies\n\n**The deal — structuring the investment:**\n\n- How much capital is needed, and in what tranches?\n- What milestones trigger each tranche?\n- What are the expected returns if things go well?\n- What is the investor's exit path (IPO, acquisition, dividend)?\n\n> The best deals are structured so that **everyone's incentives are aligned**: founders, investors, and employees all benefit when the venture succeeds, and all share downside risk. Misaligned incentives are among the most common causes of venture failure after initial investment."
        },
      ],
    },
    {
      label: "Camuffo et al. (2020)",
      citation: "Camuffo, A., Cordova, A., Gambardella, A., & Spina, C. (2020). A Scientific Approach to Entrepreneurial Decision Making: Evidence from a Randomized Control Trial. Management Science, 66(2), 564–586.",
      sections: [
        {
          title: "Framework & Theory",
          body: "Camuffo et al. propose that entrepreneurs should approach venture development as **scientists** — formulating hypotheses, designing experiments, and updating beliefs based on evidence.\n\n**The core argument:** Entrepreneurial decision-making is fundamentally a problem of decision-making under uncertainty. The scientific method — hypothesis formulation, testing, and Bayesian updating — is well-suited to reduce this uncertainty efficiently.\n\n**Two approaches to entrepreneurial decision-making:**\n\n- **Effectuation** (Sarasvathy, 2001) — Start with what you have (means, not ends); let the goal emerge from experimentation and network interactions; avoid prediction, embrace contingency\n\n- **Scientific approach** — Define the goal first; derive testable hypotheses from a causal theory; run experiments; update the theory based on results\n\nThe authors argue that the scientific approach leads to **better decisions** because it forces entrepreneurs to:\n\n1. Make their causal assumptions explicit\n2. Identify the key uncertainties that determine success or failure\n3. Design efficient tests targeting those uncertainties\n4. Update beliefs rigorously rather than selectively\n\n> The scientific approach does not mean pursuing only safe, proven ideas. It means being **rigorous about what you believe and why**, and updating those beliefs when evidence contradicts them."
        },
        {
          title: "RCT Design",
          body: "The paper uses a **Randomized Control Trial (RCT)** — the gold standard for causal inference — to test whether scientific training improves entrepreneurial outcomes.\n\n**Study design:**\n\n- Sample: ~116 early-stage Italian entrepreneurs enrolled in a startup accelerator\n- Random assignment: half received training in the scientific approach (treatment group); half received standard accelerator support (control group)\n- Duration: ~6 months of program + follow-up tracking\n\n**Scientific approach training included:**\n\n- Defining a clear theory of the business (causal model)\n- Identifying key hypotheses derived from the theory\n- Designing experiments to test those hypotheses\n- Updating beliefs based on experimental results\n\n**Outcome measures:**\n\n- Revenue generated during/after the program\n- Pivots (number and quality of strategic changes)\n- Persistence (whether ventures continued operating)\n- Speed of learning (how quickly teams updated strategies)\n\n> The RCT design is methodologically significant: it allows the authors to **causally attribute** differences in outcomes to the scientific approach, ruling out selection effects (e.g., better entrepreneurs self-selecting into scientific thinking)."
        },
        {
          title: "Key Findings",
          body: "**Main result:** Entrepreneurs trained in the scientific approach **significantly outperformed** the control group on multiple dimensions.\n\n**Specific findings:**\n\n- **Revenue:** Treatment group generated substantially higher revenue during and after the program period\n\n- **Pivots:** Treatment group pivoted more — and their pivots were more strategically sound (they changed direction when evidence demanded it, rather than persisting with failed assumptions)\n\n- **Abandonment:** Treatment group was **more willing to abandon** ventures that the evidence showed were unviable — freeing resources for better opportunities\n\n- **Speed:** Treatment group updated beliefs and strategies faster in response to new information\n\n**Mechanism — why does it work?**\n\nThe scientific approach forces entrepreneurs to separate their **beliefs** from their **identity**. Non-scientific entrepreneurs often conflate the two — abandoning a hypothesis feels like admitting personal failure. Scientific entrepreneurs see a failed hypothesis as valuable information, not personal defeat.\n\n> \"Entrepreneurs who think like scientists are more likely to pivot when they should, and more likely to persevere when they should — because their decisions are driven by evidence rather than ego.\"\n\n**Surprising finding:** The treatment effect was strongest among entrepreneurs with **more prior experience** — suggesting that the scientific approach is complementary to, not a substitute for, domain expertise."
        },
        {
          title: "Implications for Entrepreneurs",
          body: "**Practical implications of Camuffo et al. (2020):**\n\n**1. Make your causal model explicit**\n\nBefore running experiments, write down your theory of why the venture will work. What causes what? If customers see X, they will do Y because of Z. Making this explicit surfaces hidden assumptions.\n\n**2. Derive falsifiable hypotheses**\n\nA hypothesis that cannot be falsified is not useful. State in advance what evidence would cause you to change your mind. \"If fewer than 10% of landing page visitors sign up, the value proposition needs rethinking.\"\n\n**3. Prioritize by uncertainty × impact**\n\nNot all assumptions are equally important. Focus experiments on assumptions that are:\n- **Highly uncertain** (you genuinely don't know if they're true)\n- **High impact** (if wrong, the model fails)\n\n**4. Update beliefs honestly**\n\nThe biggest failure mode is collecting evidence and then rationalizing it to fit your prior beliefs. The scientific approach requires **Bayesian updating** — your new belief should reflect both your prior and the new evidence.\n\n**5. Distinguish learning from pivoting**\n\nNot every failed hypothesis should trigger a pivot. Sometimes you learn that an assumption was right but the execution was wrong. The scientific approach helps distinguish between **theory failure** and **execution failure**.\n\n> **Connection to Week 5 themes:** The scientific approach operationalizes the \"hypothesis-driven entrepreneurship\" cycle from the lecture — it provides the rigorous underpinning that makes MVP testing more than just fast iteration."
        },
      ],
    },
  ],
  sideLabels: {
    lecture: [
      "The Entrepreneurial Process & Business Models",
      "Business Model Canvas",
      "Validating Assumptions: Why It Matters",
      "The Business Plan Debate",
      "Hypothesis-Driven Entrepreneurship & MVP",
      "Zipcar Case: Business Model & Investor Assessment",
      "Zipcar Fishbone Analysis",
      "Conclusions & Key Steps",
    ],
    paper0: [
      "The Framework: People, Opportunity, Context, Risk & Reward",
      "People",
      "Opportunity",
      "Context",
      "Risk & Reward and the Deal",
    ],
    paper1: [
      "Framework & Theory",
      "RCT Design",
      "Key Findings",
      "Implications for Entrepreneurs",
    ],
  },
});
